UNIT_2 = {
    "unit_id": "cg-unit-2",
    "unit_number": 2,
    "subject": "Computer Graphics & Multimedia",
    "title": "CG Unit 2 — Rapid Revision",
    "subtitle": "Output primitives · 2D transformations · Clipping",
    "course": "M.Sc CS Sem-IV · MGSU Bikaner",
    "topics": [
        {
            "id": "bresenham",
            "number": 1,
            "title": "Bresenham's Line Algorithm",
            "analogy": "Same staircase climb as DDA, but the choice \"go flat or climb?\" is decided with whole numbers only — no decimals anywhere.",
            "definition": "Bresenham's line algorithm draws a line using only integer calculations; a decision parameter p decides at every step whether the next pixel is straight (x+1, y) or diagonal (x+1, y+1).",
            "working": [
                "Compute Δx, Δy. Initial decision: p₀ = 2Δy − Δx  (for slope |m| < 1).",
                "If p < 0 → next pixel (x+1, y), new p = p + 2Δy.",
                "If p ≥ 0 → next pixel (x+1, y+1), new p = p + 2Δy − 2Δx.",
                "Repeat Δx times until the end point.",
            ],
            "diagram_key": "dda-grid",
            "diagram_caption": "Same line (2,3)→(8,6) — Bresenham picks the same pixels, with integers only",
            "quick_facts": [
                "Only + and − on integers → faster and more accurate than DDA (no rounding error). Used in hardware.",
            ],
            "comparison": {
                "title": "★ DDA vs Bresenham (very common 5-marker)",
                "headers": ["Point", "DDA", "Bresenham"],
                "rows": [
                    ["Arithmetic", "Floating point", "Integer only"],
                    ["Operations", "Division + rounding", "Addition/subtraction only"],
                    ["Accuracy", "Small rounding error", "Exact"],
                    ["Speed", "Slower", "Faster"],
                ],
            },
            "formulas": ["p₀ = 2Δy − Δx · p<0: p += 2Δy · p≥0: p += 2Δy − 2Δx, y+1"],
            "memory_trick": "p negative → stay flat. p positive → climb diagonal.",
            "exam_tip": None,
            "solved_example": {
                "title": "Solved: (2, 3) → (8, 6)",
                "given": "Δx = 6, Δy = 3 → p₀ = 2(3) − 6 = 0 · add +6 if p<0, add −6 if p≥0 (with y+1)",
                "steps": [],
                "table": {
                    "headers": ["k", "p", "p < 0 ?", "Plot"],
                    "rows": [
                        ["–", "–", "start", "(2, 3)"],
                        ["1", "0", "No → diagonal", "(3, 4)"],
                        ["2", "−6", "Yes → straight", "(4, 4)"],
                        ["3", "0", "No → diagonal", "(5, 5)"],
                        ["4", "−6", "Yes → straight", "(6, 5)"],
                        ["5", "0", "No → diagonal", "(7, 6)"],
                        ["6", "−6", "Yes → straight", "(8, 6)"],
                    ],
                },
                "note": "Same 7 pixels as DDA but zero decimals — that is Bresenham's whole advantage.",
            },
        },
        {
            "id": "midpoint-circle",
            "number": 2,
            "title": "Midpoint Circle Algorithm",
            "analogy": "Draw only one pizza slice (1/8 of the circle) and mirror it 8 times to finish the whole pizza.",
            "definition": "The midpoint circle algorithm plots a circle by testing whether the midpoint between two candidate pixels lies inside or outside the circle (integer decision parameter p). Only one octant is computed; the rest come from 8-way symmetry.",
            "working": [
                "Start at (0, r) with p₀ = 1 − r.",
                "If p < 0 → next (x+1, y), new p = p + 2x + 1 (x already increased).",
                "If p ≥ 0 → next (x+1, y−1), new p = p + 2x + 1 − 2y.",
                "Stop when x ≥ y. Mirror every point to all 8 octants: (±x, ±y) and (±y, ±x).",
            ],
            "diagram_key": "circle-octants",
            "diagram_caption": "Compute 1 octant → mirror to 8 (8-way symmetry)",
            "quick_facts": [
                "One computed point instantly gives 8 circle points — that is why it is fast.",
            ],
            "formulas": ["p₀ = 1 − r · start (0, r) · stop when x ≥ y"],
            "comparison": None,
            "memory_trick": "1 slice, 8 mirrors. p₀ = 1 − r.",
            "exam_tip": None,
            "solved_example": {
                "title": "Solved: circle r = 5, centre (0, 0)",
                "given": "Start (0, 5) · p₀ = 1 − r = −4",
                "steps": [],
                "table": {
                    "headers": ["k", "p", "Next (x, y)"],
                    "rows": [
                        ["0", "p₀ = −4 (< 0)", "(1, 5)"],
                        ["1", "−4 + 2(1)+1 = −1 (< 0)", "(2, 5)"],
                        ["2", "−1 + 2(2)+1 = 4 (≥ 0)", "(3, 4)  y−1"],
                        ["3", "4 + 2(3)+1 − 2(4) = 3", "(4, 3) → stop (x ≥ y)"],
                    ],
                },
                "note": "Octant points: (0,5)(1,5)(2,5)(3,4)(4,3) → mirror to all 8 octants for the full circle.",
            },
        },
        {
            "id": "polygon-fill",
            "number": 3,
            "title": "Polygon Filling",
            "analogy": "Colouring inside a shape: rule lines row by row (scan-line), or pour paint at one inside point and let it spread till the wall (flood/boundary fill).",
            "definition": "Polygon filling colours all pixels inside a polygon. Main methods: Scan-line fill, Boundary fill and Flood fill.",
            "working": [
                "Scan-line: for each row, find where it crosses the polygon edges, sort the crossings, fill between PAIRS.",
                "Boundary fill: start from an inside seed pixel, spread in 4 or 8 directions, STOP at the boundary colour.",
                "Flood fill: spread from seed, replacing every pixel that still has the OLD interior colour.",
            ],
            "diagram_key": "scanline-fill",
            "diagram_caption": "Scan-line fill: colour between pairs of edge intersections",
            "quick_facts": [
                "4-connected spreads ↑↓←→ ; 8-connected also spreads diagonally.",
                "Boundary fill needs the border colour; flood fill needs the old area colour.",
            ],
            "formulas": [],
            "comparison": None,
            "memory_trick": "Scan-line = ruler rows. Boundary = stop at wall. Flood = replace old colour.",
            "exam_tip": None,
            "solved_example": None,
        },
        {
            "id": "transforms",
            "number": 4,
            "title": "2D Transformations (T · R · S)",
            "analogy": "A photo on a table: slide it (translate), spin it (rotate), zoom it (scale).",
            "definition": "A 2D transformation changes the position, orientation or size of an object using simple equations/matrices. The three basic ones are Translation, Rotation and Scaling.",
            "working": [
                "Translation (slide): x' = x + tx,  y' = y + ty.",
                "Rotation about origin (turn by θ): x' = x·cosθ − y·sinθ,  y' = x·sinθ + y·cosθ.",
                "Scaling (zoom): x' = sx·x,  y' = sy·y  (sx = sy → uniform).",
            ],
            "diagram_key": "transforms-2d",
            "diagram_caption": "Translate = slide · Rotate = turn · Scale = zoom",
            "quick_facts": [
                "Rotation and scaling are about the ORIGIN by default. s > 1 enlarges, s < 1 shrinks.",
            ],
            "formulas": ["T: x'=x+tx · R: x'=xcosθ−ysinθ, y'=xsinθ+ycosθ · S: x'=sx·x"],
            "comparison": None,
            "memory_trick": "T-R-S = move, turn, zoom. Translation ADDS, scaling MULTIPLIES.",
            "exam_tip": "Write the rotation equations carefully — the minus sign sits with sinθ in x'.",
            "solved_example": None,
        },
        {
            "id": "reflect-shear",
            "number": 5,
            "title": "Reflection & Shear",
            "analogy": "Reflection = mirror image. Shear = pushing the top of a card deck sideways so it slants.",
            "definition": "Reflection produces a mirror image of an object about an axis. Shear slants an object by shifting one coordinate in proportion to the other.",
            "working": [
                "Reflect about x-axis: (x, y) → (x, −y). About y-axis: (−x, y).",
                "About origin: (−x, −y). About line y = x: (y, x).",
                "Shear-x: x' = x + shx·y, y' = y.  Shear-y: y' = y + shy·x, x' = x.",
            ],
            "diagram_key": "reflect-shear",
            "diagram_caption": "Mirror about x-axis · shear-x slants the shape",
            "quick_facts": [
                "Reflection = scaling with −1. Shear keeps one coordinate unchanged.",
            ],
            "formulas": ["x-axis (x,−y) · y-axis (−x,y) · y=x (y,x) · shear-x: x'=x+shx·y"],
            "comparison": None,
            "memory_trick": "Mirror flips the SIGN; shear ADDS the other coordinate.",
            "exam_tip": None,
            "solved_example": None,
        },
        {
            "id": "homogeneous",
            "number": 6,
            "title": "Homogeneous Coordinates & Composite Transforms",
            "analogy": "Add a dummy 1 to every point — now every move (even sliding) becomes multiplication, so many moves can be squeezed into ONE matrix.",
            "definition": "Homogeneous coordinates write point (x, y) as (x, y, 1) so every transformation, including translation, becomes a 3×3 matrix multiplication. A composite transformation multiplies several such matrices into one.",
            "working": [
                "(x, y) → (x, y, 1); all of T, R, S become 3×3 matrices.",
                "Composite: with column vectors (P' = M·P), applying M1 then M2 gives M = M2 · M1 — matrices apply RIGHT to LEFT.",
                "Rotation about arbitrary point P: translate P to origin → rotate → translate back:  T(P) · R(θ) · T(−P).",
            ],
            "diagram_key": None,
            "diagram_caption": None,
            "quick_facts": [
                "Why needed: translation is addition, not multiplication — homogeneous form fixes this mismatch.",
                "Matrix order matters: R·T ≠ T·R.",
            ],
            "formulas": ["P' = M · [x y 1]ᵀ · about point P: T(P) · R(θ) · T(−P)"],
            "comparison": None,
            "memory_trick": "Add a 1, multiply everything. With column vectors, read composite order RIGHT → LEFT.",
            "exam_tip": "\"Why homogeneous coordinates?\" = to make translation also a matrix multiplication — write this line.",
            "solved_example": None,
        },
        {
            "id": "window-viewport",
            "number": 7,
            "title": "Window to Viewport Transformation",
            "analogy": "Window = the part of the world you photograph. Viewport = where you paste that photo on the screen.",
            "definition": "A window is the selected area of the picture in world coordinates; a viewport is the screen area where it is displayed. The window-to-viewport transformation maps every window point to the viewport keeping relative positions equal.",
            "working": [
                "Keep the relative position same: (xw − xwmin)/window width = (xv − xvmin)/viewport width.",
                "Scale factors: sx = (xvmax − xvmin)/(xwmax − xwmin), similarly sy.",
                "Map: xv = xvmin + (xw − xwmin)·sx,  yv = yvmin + (yw − ywmin)·sy.",
            ],
            "diagram_key": "window-viewport",
            "diagram_caption": "Window (world) → Viewport (screen)",
            "quick_facts": [
                "Different aspect ratios of window & viewport → picture gets stretched.",
            ],
            "formulas": ["sx = (xvmax − xvmin) / (xwmax − xwmin)"],
            "comparison": None,
            "memory_trick": "Window = WHAT to see. Viewport = WHERE to show.",
            "exam_tip": None,
            "solved_example": None,
        },
        {
            "id": "clipping",
            "number": 8,
            "title": "Clipping (Cohen-Sutherland & Sutherland-Hodgman)",
            "analogy": "Cutting a photo to fit a frame — anything outside the frame is trimmed off.",
            "definition": "Clipping removes the parts of a picture lying outside the window. Cohen-Sutherland clips LINES using 4-bit region codes; Sutherland-Hodgman clips POLYGONS against each window edge one by one.",
            "working": [
                "Cohen-Sutherland: give each end point a 4-bit code (Top Bottom Right Left; bit = 1 means outside that side).",
                "Codes OR = 0000 (both ends inside) → ACCEPT. Codes AND ≠ 0000 → fully outside → REJECT.",
                "Otherwise: split the line at a window edge and repeat with the inside part.",
                "Sutherland-Hodgman: clip the whole polygon against left, right, bottom, top edges one after another.",
            ],
            "diagram_key": "region-codes",
            "diagram_caption": "Cohen-Sutherland 9 regions with 4-bit codes (TBRL)",
            "quick_facts": [
                "Other line clippers: Midpoint subdivision, Liang-Barsky (parametric).",
            ],
            "formulas": [],
            "comparison": None,
            "memory_trick": "OR = 0000 → accept. AND ≠ 0000 → reject. Bits = TBRL.",
            "exam_tip": "Draw the 3×3 region-code grid — it makes the whole answer clear in seconds.",
            "solved_example": None,
        },
    ],
    "final_sections": {
        "cheat_card": {
            "read_time": "2-minute read",
            "formulas": [
                "Bresenham: p₀ = 2Δy − Δx · p<0: +2Δy · p≥0: +2Δy−2Δx, y+1",
                "Circle: p₀ = 1 − r · start (0, r) · stop x ≥ y",
                "T: x' = x + tx · S: x' = sx·x",
                "R: x' = xcosθ − ysinθ · y' = xsinθ + ycosθ",
                "Reflect: x-axis (x,−y) · y-axis (−x,y) · y=x (y,x)",
                "Shear-x: x' = x + shx·y",
                "W→V: sx = (xvmax−xvmin)/(xwmax−xwmin)",
            ],
            "hooks": [
                "Bresenham: p negative → flat, p positive → climb",
                "Circle: 1 slice, 8 mirrors",
                "Fill: Scan-line rows · Boundary stops at wall · Flood replaces old",
                "T-R-S = move, turn, zoom",
                "Homogeneous: add a 1, multiply · column vectors → read RIGHT → LEFT",
                "Window = What, Viewport = Where",
                "Clipping: OR=0 accept · AND≠0 reject · bits TBRL",
            ],
        },
        "last_minute_revision": [
            {"topic": "Bresenham Line", "line": "p₀ = 2Δy − Δx. p<0 → flat (+2Δy); p≥0 → climb (+2Δy−2Δx). Integers only, same pixels as DDA."},
            {"topic": "Midpoint Circle", "line": "p₀ = 1 − r, start (0, r), stop x ≥ y, mirror every point ×8 (8-way symmetry)."},
            {"topic": "Polygon Fill", "line": "Scan-line: fill between intersection pairs. Boundary: stop at wall colour. Flood: replace old colour."},
            {"topic": "2D Transforms", "line": "T adds (x+tx), R uses cosθ/sinθ, S multiplies (sx·x). Default = about origin."},
            {"topic": "Reflection & Shear", "line": "Mirror flips sign: x-axis (x,−y), y-axis (−x,y), y=x (y,x). Shear-x: x' = x + shx·y."},
            {"topic": "Homogeneous", "line": "(x, y, 1) → all transforms become 3×3 matrix products. With column vectors composite reads RIGHT→LEFT. Arbitrary point: T·R·T(−)."},
            {"topic": "Window/Viewport", "line": "Window = WHAT (world), Viewport = WHERE (screen). sx = (xvmax−xvmin)/(xwmax−xwmin)."},
            {"topic": "Clipping", "line": "Cohen-Sutherland: TBRL codes; OR=0 accept, AND≠0 reject, else split. Sutherland-Hodgman: polygon vs 4 edges."},
        ],
        "must_memorize": [
            {"term": "Bresenham's Algorithm", "definition": "Line-drawing algorithm using an integer decision parameter p to choose the next pixel — no floating point."},
            {"term": "Decision Parameter", "definition": "A value whose sign decides between the two candidate pixels at each step."},
            {"term": "Midpoint Circle Algorithm", "definition": "Plots one octant using the midpoint inside/outside test; the rest of the circle comes from 8-way symmetry."},
            {"term": "Scan-line Fill", "definition": "Fills a polygon row by row, colouring between pairs of edge intersections."},
            {"term": "Boundary / Flood Fill", "definition": "Boundary fill spreads from a seed until the boundary colour; flood fill replaces the old interior colour."},
            {"term": "2D Transformation", "definition": "Operation that changes position, orientation or size of an object: Translation, Rotation, Scaling."},
            {"term": "Homogeneous Coordinates", "definition": "Writing (x, y) as (x, y, 1) so every transformation becomes a 3×3 matrix multiplication."},
            {"term": "Composite Transformation", "definition": "A single matrix obtained by multiplying several transformation matrices (with column vectors, applied right to left)."},
            {"term": "Window & Viewport", "definition": "Window = selected area in world coordinates; Viewport = screen area where it is displayed."},
            {"term": "Clipping", "definition": "Removing picture parts outside the window (Cohen-Sutherland for lines, Sutherland-Hodgman for polygons)."},
        ],
    },
}
