UNIT_3 = {
    "unit_id": "cg-unit-3",
    "unit_number": 3,
    "subject": "Computer Graphics & Multimedia",
    "title": "CG Unit 3 — Rapid Revision",
    "subtitle": "3D transformations · Projections · Hidden surfaces · Curves",
    "course": "M.Sc CS Sem-IV · MGSU Bikaner",
    "topics": [
        {
            "id": "3d-concepts",
            "number": 1,
            "title": "3D Concepts & Coordinate Systems",
            "analogy": "2D is a drawing on paper; 3D adds depth — like going from a photo to a real box you can walk around.",
            "definition": "3D graphics represents objects with three coordinates (x, y, z), where z gives depth. In a right-handed system +z points towards the viewer; many display systems use a left-handed system where +z goes into the screen.",
            "working": [
                "Right-handed: curl right-hand fingers from x to y — thumb points along +z (towards you).",
                "Left-handed: +z goes INTO the screen, so bigger z = farther away (handy for depth).",
                "A 3D object is stored as vertices, edges and faces (a polygon mesh).",
                "3D pipeline: model → world → viewing → projection → 2D screen.",
            ],
            "diagram_key": "axes-3d",
            "diagram_caption": "Right-handed 3D coordinate system",
            "quick_facts": [
                "Screens are 2D — every 3D scene must be PROJECTED before display.",
            ],
            "comparison": None,
            "formulas": [],
            "memory_trick": "Right hand: thumb (+z) points AT you. Left hand: z runs AWAY into the screen.",
            "exam_tip": None,
            "solved_example": None,
        },
        {
            "id": "3d-translate-scale",
            "number": 2,
            "title": "3D Translation & Scaling",
            "analogy": "Same slide and zoom as 2D — just with one extra direction (depth).",
            "definition": "3D translation moves a point by (tx, ty, tz); 3D scaling multiplies coordinates by (sx, sy, sz). Using homogeneous coordinates (x, y, z, 1), both become 4×4 matrix multiplications.",
            "working": [
                "Translation: x' = x + tx, y' = y + ty, z' = z + tz.",
                "Scaling (about origin): x' = sx·x, y' = sy·y, z' = sz·z.",
                "Scaling about a fixed point F: translate F to origin → scale → translate back.",
                "All 3D transforms use 4×4 matrices on points written as [x y z 1]ᵀ.",
            ],
            "diagram_key": None,
            "diagram_caption": None,
            "quick_facts": [
                "Exactly the 2D rules with a z term added; homogeneous form makes everything multiplication.",
            ],
            "comparison": None,
            "formulas": ["T: (x+tx, y+ty, z+tz) · S: (sx·x, sy·y, sz·z) · P = [x y z 1]ᵀ"],
            "memory_trick": "Translation ADDS, scaling MULTIPLIES — now in 3 directions.",
            "exam_tip": None,
            "solved_example": {
                "title": "Solved: P(2, 3, 4) — translate then scale",
                "given": "T = (1, 2, 3), then S = (2, 2, 2)",
                "steps": [],
                "table": {
                    "headers": ["Step", "Rule", "Result"],
                    "rows": [
                        ["Start", "P", "(2, 3, 4)"],
                        ["T(1, 2, 3)", "add each", "(3, 5, 7)"],
                        ["S(2, 2, 2)", "multiply each", "(6, 10, 14)"],
                    ],
                },
                "note": "Order matters: scaling first would give (4, 6, 8) → then +T = (5, 8, 11), a different point.",
            },
        },
        {
            "id": "3d-rotation",
            "number": 3,
            "title": "3D Rotation (about x, y, z axes)",
            "analogy": "Spinning a skewer: the coordinate ON the axis stays fixed, the other two rotate exactly like 2D.",
            "definition": "3D rotation turns a point by angle θ about the x, y or z axis. The coordinate of the rotation axis stays unchanged; the other two follow the 2D rotation equations.",
            "working": [
                "About z-axis: x' = x·cosθ − y·sinθ, y' = x·sinθ + y·cosθ, z' = z.",
                "About x-axis: y' = y·cosθ − z·sinθ, z' = y·sinθ + z·cosθ, x' = x.",
                "About y-axis: z' = z·cosθ − x·sinθ, x' = z·sinθ + x·cosθ, y' = y.",
                "About an arbitrary axis: translate to origin → align axis → rotate → undo the steps.",
            ],
            "diagram_key": None,
            "diagram_caption": None,
            "quick_facts": [
                "Cyclic pattern x → y → z → x: same equations, letters shifted.",
            ],
            "comparison": None,
            "formulas": ["Rz: x' = xcosθ − ysinθ · y' = xsinθ + ycosθ · z' = z"],
            "memory_trick": "The axis coordinate NEVER changes. Rz is just the 2D rotation.",
            "exam_tip": "Write which coordinate stays constant first — it instantly shows you know the concept.",
            "solved_example": {
                "title": "Solved: rotate P(1, 2, 3) by 90° about z-axis",
                "given": "cos90° = 0, sin90° = 1",
                "steps": [],
                "table": {
                    "headers": ["Coordinate", "Calculation", "Result"],
                    "rows": [
                        ["x'", "1·(0) − 2·(1)", "−2"],
                        ["y'", "1·(1) + 2·(0)", "1"],
                        ["z'", "unchanged", "3"],
                    ],
                },
                "note": "P' = (−2, 1, 3). Check: distance from z-axis stays √5 before and after ✓.",
            },
        },
        {
            "id": "parallel-projection",
            "number": 4,
            "title": "Projections — Parallel",
            "analogy": "Sunlight shadows: the sun's rays are almost parallel, so a stick's shadow keeps its true proportions.",
            "definition": "Projection maps 3D points onto a 2D view plane. In parallel projection all projectors are parallel to each other; object proportions are preserved, so it is used in engineering drawings.",
            "working": [
                "Orthographic: projectors hit the view plane at 90° → top, front and side views.",
                "Oblique: projectors hit at an angle → Cavalier (full depth shown) and Cabinet (half depth).",
                "Simplest case (view plane z = 0): just drop the z coordinate → (x, y).",
            ],
            "diagram_key": "projection-tree",
            "diagram_caption": "Classification of projections",
            "quick_facts": [
                "True measurements, but no depth feeling — perfect for CAD, not for realism.",
            ],
            "comparison": None,
            "formulas": ["Orthographic on z = 0: (x, y, z) → (x, y)"],
            "memory_trick": "Parallel = engineer's view. Ortho = 90°, Oblique = slanted. CAvalier = All depth, CaBinet = half (B = ½).",
            "exam_tip": None,
            "solved_example": None,
        },
        {
            "id": "perspective-projection",
            "number": 5,
            "title": "Perspective Projection",
            "analogy": "Railway tracks appear to meet far away — farther objects look smaller, exactly how your eye sees the world.",
            "definition": "In perspective projection, projectors converge at a centre of projection (COP); distant objects appear smaller, giving a realistic view. Parallel lines appear to meet at vanishing points.",
            "working": [
                "COP at origin, view plane at z = d: x' = x·d/z, y' = y·d/z.",
                "Bigger z (farther) → smaller image: this division by z creates realism.",
                "1, 2 or 3 vanishing points depending on how many principal axes the view plane cuts.",
            ],
            "diagram_key": "parallel-vs-perspective",
            "diagram_caption": "Parallel projectors vs converging projectors (COP)",
            "quick_facts": [
                "Used in games, movies, art. Sizes are NOT true — cannot measure from it.",
            ],
            "comparison": {
                "title": "★ Parallel vs Perspective (very common 5-marker)",
                "headers": ["Point", "Parallel", "Perspective"],
                "rows": [
                    ["Projectors", "Parallel to each other", "Converge at COP"],
                    ["Object size", "True size preserved", "Shrinks with distance"],
                    ["Realism", "Low", "High (eye-like)"],
                    ["Vanishing points", "None", "1, 2 or 3"],
                    ["Used in", "Engineering / CAD", "Games, art, movies"],
                ],
            },
            "formulas": ["x' = x·d / z · y' = y·d / z (view plane z = d, COP at origin)"],
            "memory_trick": "Perspective = eye view. DIVIDE by z — far things shrink.",
            "exam_tip": None,
            "solved_example": {
                "title": "Solved: project P(6, 8, 10) onto view plane d = 5",
                "given": "COP at origin · x' = x·d/z, y' = y·d/z",
                "steps": [],
                "table": {
                    "headers": ["Coordinate", "Calculation", "Result"],
                    "rows": [
                        ["x'", "6 × 5 / 10", "3"],
                        ["y'", "8 × 5 / 10", "4"],
                    ],
                },
                "note": "P' = (3, 4). The point is twice as far as the plane (z = 10 vs d = 5), so its image is exactly half size — that is perspective.",
            },
        },
        {
            "id": "hidden-surface",
            "number": 6,
            "title": "Hidden Surface Removal",
            "analogy": "In a group photo, people in front hide those behind. The computer must decide, at every pixel, which surface stands in front.",
            "definition": "Hidden surface removal (visible surface detection) finds which parts of a 3D scene are visible from the viewpoint and removes the hidden parts. Main methods: Back-face detection, Z-buffer, Painter's algorithm.",
            "working": [
                "Back-face detection (object space): define V as the vector from the surface TOWARDS the viewer. With this convention a back-facing surface has N·V < 0 (its normal points away). If the opposite viewing-vector convention is used, the sign reverses.",
                "Z-buffer (image space): keep a depth value for every pixel; a new surface wins a pixel only if it is CLOSER (smaller z). Needs an extra depth buffer.",
                "Painter's algorithm (list priority): sort surfaces by depth and paint from FARTHEST to NEAREST — near paint covers far paint.",
            ],
            "diagram_key": "zbuffer",
            "diagram_caption": "Z-buffer: at each pixel the smaller depth (closer surface) wins",
            "quick_facts": [
                "For a closed opaque object, back-face detection can eliminate many faces that point away from the viewer — a quick first filter.",
                "Object-space methods compare OBJECTS (back-face); image-space methods work PIXEL by pixel (Z-buffer).",
                "Z-buffer handles any scene but needs extra memory; Painter's struggles with overlapping/intersecting surfaces.",
            ],
            "comparison": None,
            "formulas": ["V = surface → viewer: back face if N · V < 0 (sign reverses with the opposite V convention)"],
            "memory_trick": "Z-buffer: smallest z wins the pixel. Painter: paint far → near.",
            "exam_tip": "Always classify: back-face = object space, Z-buffer = image space — this line carries marks.",
            "solved_example": None,
        },
        {
            "id": "bezier",
            "number": 7,
            "title": "Bezier Curves",
            "analogy": "Bend a flexible ruler using magnets (control points): the ruler touches the first and last magnet and is pulled towards the middle ones.",
            "definition": "A Bezier curve is a smooth curve defined by control points: it passes through the first and last control points and is pulled towards the middle ones. A curve with n+1 control points has degree n.",
            "working": [
                "Cubic Bezier (4 points): B(u) = (1−u)³P0 + 3u(1−u)²P1 + 3u²(1−u)P2 + u³P3, for 0 ≤ u ≤ 1.",
                "The curve always lies inside the CONVEX HULL of its control points.",
                "Moving ANY control point changes the whole curve (global control).",
                "Used in fonts, car body design, animation paths (Photoshop/Illustrator pen tool).",
            ],
            "diagram_key": "bezier",
            "diagram_caption": "Cubic Bezier: hugs P0 & P3, pulled by P1 & P2 (dashed = convex hull)",
            "quick_facts": [
                "Degree = number of control points − 1. Curve is tangent to P0P1 and P2P3 at the ends.",
            ],
            "comparison": None,
            "formulas": ["Cubic: B(u) = (1−u)³P0 + 3u(1−u)²P1 + 3u²(1−u)P2 + u³P3"],
            "memory_trick": "Curve HUGS the ends, middle points only PULL. Degree = points − 1.",
            "exam_tip": None,
            "solved_example": {
                "title": "Solved: cubic Bezier at u = 0.5",
                "given": "P0(0,0), P1(2,4), P2(6,4), P3(8,0) · at u = 0.5 coefficients = 1/8, 3/8, 3/8, 1/8",
                "steps": [],
                "table": {
                    "headers": ["Coordinate", "Calculation", "Result"],
                    "rows": [
                        ["x", "(0 + 3·2 + 3·6 + 8) / 8 = 32/8", "4"],
                        ["y", "(0 + 3·4 + 3·4 + 0) / 8 = 24/8", "3"],
                    ],
                },
                "note": "B(0.5) = (4, 3). Shortcut worth memorising: at u = 0.5, B = (P0 + 3P1 + 3P2 + P3) / 8.",
            },
        },
        {
            "id": "bspline",
            "number": 8,
            "title": "B-Spline Curves & Comparison",
            "analogy": "A long train: shifting one compartment bends only its own part of the track — the rest of the route stays the same.",
            "definition": "A B-spline curve is a smooth curve built from control points where each point influences only its local region (local control). Its degree is chosen independently of the number of control points.",
            "working": [
                "The curve is made of polynomial segments joined smoothly at knots.",
                "Moving one control point reshapes only the nearby segments — LOCAL control.",
                "Degree (commonly cubic) does not grow when you add more control points.",
            ],
            "diagram_key": None,
            "diagram_caption": None,
            "quick_facts": [
                "B-spline generalises Bezier: a Bezier curve is a special case of a B-spline.",
            ],
            "comparison": {
                "title": "★ Bezier vs B-Spline (common 5-marker)",
                "headers": ["Point", "Bezier", "B-Spline"],
                "rows": [
                    ["Control", "Global (one point moves whole curve)", "Local (only nearby part moves)"],
                    ["Degree", "= control points − 1", "Independent of point count"],
                    ["Passes through ends", "Yes (P0 and Pn)", "Not necessarily"],
                    ["Editing", "Harder for long curves", "Easy, precise local edits"],
                ],
            },
            "formulas": [],
            "memory_trick": "B-spline = Local boss. Bezier = Global boss.",
            "exam_tip": "If asked \"why B-spline over Bezier?\" → write LOCAL CONTROL + degree independent of points.",
            "solved_example": None,
        },
    ],
    "final_sections": {
        "cheat_card": {
            "read_time": "2-minute read",
            "formulas": [
                "3D point = [x y z 1]ᵀ · all transforms = 4×4 matrices",
                "T: (x+tx, y+ty, z+tz) · S: (sx·x, sy·y, sz·z)",
                "Rz: x' = xcosθ − ysinθ · y' = xsinθ + ycosθ · z same",
                "Perspective: x' = x·d/z · y' = y·d/z",
                "Back-face (V = towards viewer): N·V < 0 → hidden",
                "Cubic Bezier at u=0.5: B = (P0 + 3P1 + 3P2 + P3) / 8",
                "Bezier degree = control points − 1",
            ],
            "hooks": [
                "Rotation: the axis coordinate never changes",
                "Parallel = engineer (true size) · Perspective = eye (÷ z, far shrinks)",
                "CAvalier = All depth · CaBinet = half",
                "Z-buffer: smallest z wins the pixel · Painter: far → near",
                "Back-face = object space · Z-buffer = image space",
                "Bezier: hugs ends, middles pull, GLOBAL · B-spline: LOCAL control",
            ],
        },
        "last_minute_revision": [
            {"topic": "3D Concepts", "line": "Point = (x, y, z); right-handed z towards you. Pipeline: model → world → view → projection → screen."},
            {"topic": "3D T & S", "line": "T adds (x+tx, y+ty, z+tz); S multiplies (sx·x…). 4×4 matrices on [x y z 1]. (2,3,4) +T(1,2,3) = (3,5,7)."},
            {"topic": "3D Rotation", "line": "Axis coordinate fixed; other two = 2D equations. Rz 90° of (1,2,3) → (−2, 1, 3)."},
            {"topic": "Parallel Projection", "line": "Parallel projectors, true size, engineering. Orthographic (90°) vs Oblique (Cavalier full / Cabinet half depth)."},
            {"topic": "Perspective", "line": "Projectors meet at COP; x' = x·d/z (far shrinks); vanishing points 1–3. P(6,8,10), d=5 → (3,4)."},
            {"topic": "Hidden Surfaces", "line": "Back-face (V = towards viewer): N·V < 0 hidden (object space). Z-buffer: per-pixel depth, closest wins (image space). Painter: far → near."},
            {"topic": "Bezier", "line": "Hugs P0/Pn, convex hull, GLOBAL control, degree = n−1. At u=0.5: (P0+3P1+3P2+P3)/8."},
            {"topic": "B-Spline", "line": "LOCAL control, degree independent of points, may not touch end points. Bezier is its special case."},
        ],
        "must_memorize": [
            {"term": "3D Transformation", "definition": "Changing position/size/orientation of 3D objects using 4×4 homogeneous matrices on (x, y, z, 1)."},
            {"term": "Projection", "definition": "Mapping 3D points onto a 2D view plane so they can be displayed on screen."},
            {"term": "Parallel Projection", "definition": "All projectors parallel; preserves true size; used in engineering drawings."},
            {"term": "Perspective Projection", "definition": "Projectors converge at the centre of projection; far objects look smaller; x' = x·d/z."},
            {"term": "Vanishing Point", "definition": "Point where parallel lines appear to meet in a perspective view."},
            {"term": "Hidden Surface Removal", "definition": "Finding the visible surfaces of a 3D scene and removing the parts hidden from the viewer."},
            {"term": "Back-face Detection", "definition": "Object-space method discarding faces whose normal points away from the viewer: with V = vector towards the viewer, back face if N·V < 0."},
            {"term": "Z-buffer Algorithm", "definition": "Image-space method keeping a depth value per pixel; the closest surface (smallest z) wins each pixel."},
            {"term": "Bezier Curve", "definition": "Smooth curve through its first & last control points, pulled by the middle ones; degree = points − 1; convex-hull property."},
            {"term": "B-Spline Curve", "definition": "Piecewise curve with local control; degree independent of the number of control points."},
        ],
    },
}
