UNIT_5 = {
    "unit_id": "cg-unit-5",
    "unit_number": 5,
    "subject": "Computer Graphics & Multimedia",
    "title": "CG Unit 5 — Rapid Revision",
    "subtitle": "JPEG & MPEG · Huffman · CD/DVD · Streaming · VR/AR · Project stages",
    "course": "M.Sc CS Sem-IV · MGSU Bikaner",
    "topics": [
        {
            "id": "jpeg",
            "number": 1,
            "title": "JPEG Image Compression",
            "analogy": "Summarising a photo like class notes: keep the main points (broad shapes), drop the tiny details the eye will never miss.",
            "definition": "JPEG is a lossy image-compression standard for photographs. It converts image blocks into frequency data (DCT), discards detail the eye barely notices (quantization), and encodes the result compactly (zig-zag + RLE + Huffman).",
            "working": [
                "Convert RGB → YCbCr (eye is less sensitive to colour than brightness).",
                "Divide the image into 8×8 pixel blocks.",
                "Apply DCT (Discrete Cosine Transform) to each block → frequency values.",
                "Quantization: divide & round the values — the MAIN lossy step where detail is thrown away.",
                "Zig-zag ordering + RLE + Huffman coding → final compact .jpg file.",
            ],
            "diagram_key": "jpeg-pipeline",
            "diagram_caption": "JPEG pipeline — quantization is the main lossy step",
            "quick_facts": [
                "Quantization is the main lossy step; chroma subsampling may also discard some colour detail.",
                "Typical ratio ~10:1 with barely visible loss. Great for photos; bad for sharp text/line art (use PNG there).",
            ],
            "comparison": None,
            "formulas": ["Typical JPEG compression ≈ 10 : 1"],
            "memory_trick": "Steps: Blocks → DCT → Quantize → Zig-zag → Huffman.",
            "exam_tip": "Main information loss → QUANTIZATION (chroma subsampling may also discard some colour detail).",
            "solved_example": None,
        },
        {
            "id": "mpeg",
            "number": 2,
            "title": "MPEG Video Compression (I, P, B frames)",
            "analogy": "Instead of redrawing the whole classroom every second, just note WHO MOVED since the last look.",
            "definition": "MPEG is a lossy video-compression standard that removes spatial redundancy inside frames (JPEG-style) and temporal redundancy between frames using I, P and B frames with motion compensation.",
            "working": [
                "I-frame (Intra): a complete, self-contained image — compressed like JPEG.",
                "P-frame (Predicted): predicted from a previous I/P reference frame; stores the residual changes.",
                "B-frame (Bidirectional): predicted using the previous AND next reference frames; stores residual information — usually the smallest.",
                "Frames are grouped into a GOP (Group of Pictures); motion vectors describe how blocks moved.",
            ],
            "diagram_key": "mpeg-frames",
            "diagram_caption": "A GOP: I-frame anchors, P looks back, B looks both ways",
            "quick_facts": [
                "MPEG-1 → VCD & MP3 audio · MPEG-2 → DVD/TV · MPEG-4 = compression standard; MP4 = container format that commonly carries MPEG-4 video.",
            ],
            "comparison": {
                "title": "★ I vs P vs B frames (common 5-marker)",
                "headers": ["Point", "I-frame", "P-frame", "B-frame"],
                "rows": [
                    ["Coded from", "Itself only", "Previous reference frame", "Previous + next references"],
                    ["Size", "Largest", "Medium", "Usually smallest"],
                    ["Playback can start here?", "Yes", "No", "No"],
                ],
            },
            "formulas": [],
            "memory_trick": "I = Independent · P = Past · B = Both directions.",
            "exam_tip": None,
            "solved_example": None,
        },
        {
            "id": "huffman",
            "number": 3,
            "title": "Huffman Coding",
            "analogy": "Nicknames: your best friend gets a 1-letter name, a rare acquaintance keeps the full name — total speaking time drops.",
            "definition": "Huffman coding is a lossless compression technique that gives SHORT binary codes to frequent symbols and LONGER codes to rare ones, using a binary tree built by repeatedly merging the two smallest probabilities.",
            "working": [
                "List all symbols with their probabilities.",
                "Merge the TWO SMALLEST into one node (add probabilities).",
                "Repeat until a single root of 1.0 remains.",
                "Label branches 0 / 1; read each symbol's code from root to leaf.",
            ],
            "diagram_key": "huffman-tree",
            "diagram_caption": "Huffman tree for A(0.4) B(0.3) C(0.2) D(0.1)",
            "quick_facts": [
                "No symbol's code is a prefix of another (prefix property) → decoding is never confused.",
            ],
            "comparison": None,
            "formulas": ["Average length = Σ (probability × code bits)"],
            "memory_trick": "Frequent = short, rare = long. Always merge the two SMALLEST first.",
            "exam_tip": None,
            "solved_example": {
                "title": "Solved: A(0.4), B(0.3), C(0.2), D(0.1)",
                "given": "Merges: C+D = 0.3 → B+(CD) = 0.6 → A+(0.6) = 1.0",
                "steps": [],
                "table": {
                    "headers": ["Symbol", "Probability", "Code", "Bits"],
                    "rows": [
                        ["A", "0.4", "0", "1"],
                        ["B", "0.3", "10", "2"],
                        ["C", "0.2", "110", "3"],
                        ["D", "0.1", "111", "3"],
                    ],
                },
                "note": "Average = 0.4×1 + 0.3×2 + 0.2×3 + 0.1×3 = 1.9 bits/symbol vs 2 bits fixed-length — compression with ZERO loss.",
            },
        },
        {
            "id": "cd-dvd",
            "number": 4,
            "title": "Storage Media: CD-ROM & DVD",
            "analogy": "A vinyl record read with light: a laser follows one long spiral of microscopic bumps instead of a needle in a groove.",
            "definition": "CD-ROM and DVD are optical storage media where data is stored as pits and lands along a spiral track and read by a laser beam. CD holds ≈ 700 MB; a single-layer DVD holds ≈ 4.7 GB.",
            "working": [
                "Pits and lands reflect the laser differently → read as 0s and 1s.",
                "DVD uses a shorter-wavelength laser → smaller pits + tighter spiral → more data.",
                "DVD can be dual-layer and double-sided: 4.7 → 8.5 → up to 17 GB.",
                "Speed: 1x CD = 150 KB/s (e.g., 52x = 7.8 MB/s).",
            ],
            "diagram_key": "cd-dvd",
            "diagram_caption": "One spiral track of pits & lands, read by a laser",
            "quick_facts": [
                "CD-R = write once, CD-RW = rewritable; same idea for DVD±R/RW.",
            ],
            "comparison": {
                "title": "★ CD vs DVD (common 5-marker)",
                "headers": ["Point", "CD", "DVD"],
                "rows": [
                    ["Capacity", "≈ 700 MB", "4.7 GB (up to 17 GB)"],
                    ["Laser", "Infrared, 780 nm", "Red, 650 nm (smaller pits)"],
                    ["Spiral track", "Wider pitch", "Much tighter pitch"],
                    ["Typical use", "Audio, small data", "Movies, big software"],
                ],
            },
            "formulas": ["MP3 size = bitrate × seconds ÷ 8"],
            "memory_trick": "Smaller pits + tighter spiral = bigger capacity. Memorise the pair: CD 700 MB · DVD 4.7 GB.",
            "exam_tip": None,
            "solved_example": {
                "title": "Solved: how many MP3 songs fit on a 700 MB CD?",
                "given": "Song = 3.5 min (210 s) at 128 kbps",
                "steps": [],
                "table": {
                    "headers": ["Step", "Calculation", "Result"],
                    "rows": [
                        ["Bits per song", "1,28,000 × 210", "2,68,80,000 bits"],
                        ["Bytes", "÷ 8", "≈ 3.36 MB"],
                        ["Songs on CD", "700 ÷ 3.36", "≈ 208 songs"],
                    ],
                },
                "note": "The same CD holds only ~80 minutes of UNCOMPRESSED audio — MP3's ~10× compression is what makes 200+ songs possible.",
            },
        },
        {
            "id": "streaming",
            "number": 5,
            "title": "Streaming & Video-on-Demand",
            "analogy": "Bucket vs tap: downloading = fill the whole bucket before drinking; streaming = drink straight from the tap while water keeps flowing.",
            "definition": "Streaming delivers audio/video over a network in a continuous flow so playback starts almost immediately while the rest keeps arriving. Video-on-Demand (VoD) lets users watch any stored video whenever they want.",
            "working": [
                "Server sends the compressed stream over the network.",
                "Player first stores a few seconds in a BUFFER, then plays while downloading continues.",
                "The buffer absorbs network hiccups; adaptive streaming lowers quality when bandwidth drops.",
                "Video conferencing = two-way LIVE audio + video — needs very low delay.",
            ],
            "diagram_key": "streaming",
            "diagram_caption": "Server → network → buffer → player (plays while the rest arrives)",
            "quick_facts": [
                "Examples: YouTube/Netflix = VoD streaming; Zoom/Meet = video conferencing.",
            ],
            "comparison": None,
            "formulas": ["Download time = file size ÷ network speed"],
            "memory_trick": "Streaming = play while it arrives; the buffer is the safety tank.",
            "exam_tip": None,
            "solved_example": {
                "title": "Solved: download vs stream a 230 MB video on 2 Mbps",
                "given": "230 MB = 230 × 8 = 1840 megabits",
                "steps": [],
                "table": {
                    "headers": ["Step", "Calculation", "Result"],
                    "rows": [
                        ["Download time", "1840 ÷ 2 Mbps", "920 s"],
                        ["In minutes", "920 ÷ 60", "≈ 15.3 min wait"],
                        ["Streaming", "buffer a few seconds", "starts almost instantly"],
                    ],
                },
                "note": "This 15-minute-vs-instant contrast is the perfect one-line answer to \"why streaming?\"",
            },
        },
        {
            "id": "vr-ar",
            "number": 6,
            "title": "Virtual Reality & Augmented Reality",
            "analogy": "VR = diving fully underwater into a new world. AR = wearing goggles that draw fish swimming around your real room.",
            "definition": "Virtual Reality (VR) is a computer-generated 3D environment the user can enter and interact with using devices like a head-mounted display (HMD) and data gloves. Augmented Reality (AR) overlays computer images onto the REAL world.",
            "working": [
                "HMD shows a slightly different image to each eye → stereo depth.",
                "Head tracking updates the view instantly as the user turns → immersion.",
                "Data gloves / controllers track hand movements for interaction.",
                "Immersive VR = HMD + tracking; non-immersive = 3D world on a normal monitor.",
            ],
            "diagram_key": "vr-setup",
            "diagram_caption": "VR loop: movements go in, stereo images + sound come back",
            "quick_facts": [
                "Applications: pilot & surgery training, architecture walkthroughs, games, education.",
            ],
            "comparison": {
                "title": "★ VR vs AR (common 5-marker)",
                "headers": ["Point", "VR", "AR"],
                "rows": [
                    ["World shown", "Fully computer-made", "Real world + overlay"],
                    ["Device", "HMD (closed headset)", "Phone camera / smart glasses"],
                    ["User cut off from reality?", "Yes", "No"],
                    ["Example", "Flight simulator, VR games", "Pokemon-Go, camera filters"],
                ],
            },
            "formulas": [],
            "memory_trick": "VR Replaces the world · AR Adds to the world.",
            "exam_tip": None,
            "solved_example": None,
        },
        {
            "id": "mm-project",
            "number": 7,
            "title": "Multimedia Project Development Stages",
            "analogy": "Building a house: plan on paper, design the rooms, construct it, check every switch, then hand over the keys.",
            "definition": "A multimedia project is developed in five stages: Planning & Costing, Design & Prototyping, Production, Testing, and Delivery.",
            "working": [
                "Planning: idea, target audience, budget, team, storyboard (frame-by-frame sketch plan).",
                "Design: structure, navigation map, look & feel, working prototype.",
                "Production: create and assemble all media in an authoring tool.",
                "Testing: alpha (in-house) then beta (real users); fix bugs.",
                "Delivery: publish on CD/web/app + documentation and user support.",
            ],
            "diagram_key": None,
            "diagram_caption": None,
            "quick_facts": [
                "Team roles: project manager, writer, graphic artist, audio/video specialist, programmer.",
            ],
            "comparison": None,
            "formulas": [],
            "memory_trick": "P-D-P-T-D: Please Don't Panic — Test & Deliver.",
            "exam_tip": "Storyboard is the favourite short-note here: 'a sketch of every screen before production begins.'",
            "solved_example": None,
        },
        {
            "id": "file-formats",
            "number": 8,
            "title": "Multimedia File Formats (Summary)",
            "analogy": "File extensions are like surnames — they instantly tell you which family (media type) a file belongs to.",
            "definition": "A file format defines how a media type is stored and compressed. Every multimedia element has standard formats, e.g., JPEG for photos, MP3 for music, MP4 for video.",
            "working": [
                "Text: TXT, DOC, PDF, HTML.",
                "Image: BMP (uncompressed), JPEG (lossy photos), GIF (256 colours + animation), PNG (lossless + transparency), TIFF (printing).",
                "Audio: WAV (uncompressed), MP3 (lossy), MIDI (note instructions only).",
                "Video: AVI, MOV, MP4/MPEG (compressed), WEBM (web).",
            ],
            "diagram_key": None,
            "diagram_caption": None,
            "quick_facts": [
                "Choosing fast: photo → JPEG · logo/transparency → PNG · song → MP3 · movie → MP4.",
            ],
            "comparison": None,
            "formulas": [],
            "memory_trick": "The 4 everyday champions: JPEG (photo), PNG (logo), MP3 (song), MP4 (movie).",
            "exam_tip": "Short note on file formats = 3 formats per media type, one line each — quick full marks.",
            "solved_example": None,
        },
    ],
    "final_sections": {
        "predicted_questions": [
            {"question": "Explain JPEG compression with a block diagram.", "marks": "10", "topic_id": "jpeg", "reason": "The pipeline diagram is a ready-made answer"},
            {"question": "Explain MPEG video compression (I, P and B frames).", "marks": "10", "topic_id": "mpeg", "reason": "GOP diagram + the I/P/B table"},
            {"question": "Explain Huffman coding with an example.", "marks": "10", "topic_id": "huffman", "reason": "The solved tree (avg 1.9 bits) fits exactly"},
            {"question": "Differentiate Virtual Reality and Augmented Reality.", "marks": "5", "topic_id": "vr-ar", "reason": "Star table + one device example each"},
            {"question": "Explain the stages of multimedia project development.", "marks": "10", "topic_id": "mm-project", "reason": "P-D-P-T-D — five stages, one line each"},
        ],
        "cheat_card": {
            "read_time": "2-minute read",
            "formulas": [
                "Huffman avg = Σ(prob × bits) — example: 1.9 bits vs 2 fixed",
                "A=0 · B=10 · C=110 · D=111 (for 0.4/0.3/0.2/0.1)",
                "MP3 size = bitrate × seconds ÷ 8 (3.5 min @128k ≈ 3.36 MB)",
                "CD = 700 MB · DVD = 4.7 GB (dual/double up to 17 GB)",
                "Download time = size ÷ speed (230 MB @ 2 Mbps ≈ 15 min)",
                "JPEG ratio ≈ 10:1 · 1x CD speed = 150 KB/s",
            ],
            "hooks": [
                "JPEG: Blocks → DCT → Quantize (MAIN lossy step) → Zig-zag → Huffman",
                "MPEG: I = Independent · P = Past · B = Both",
                "Huffman: frequent = short code · merge two SMALLEST",
                "CD/DVD: smaller pits + tighter spiral = more data",
                "Streaming = play while it arrives (buffer = safety tank)",
                "VR Replaces the world · AR Adds to it",
                "Project: Plan → Design → Produce → Test → Deliver",
            ],
        },
        "last_minute_revision": [
            {"topic": "JPEG", "line": "Lossy photo standard. YCbCr → 8×8 blocks → DCT → QUANTIZE (main lossy step) → zig-zag + Huffman. ~10:1."},
            {"topic": "MPEG", "line": "I = full frame; P = predicted from a past reference (residuals); B = both references (usually smallest). GOP + motion vectors. MPEG-2 DVD; MP4 = container for MPEG-4 video."},
            {"topic": "Huffman", "line": "Lossless; merge two smallest; frequent = short code. A0 B10 C110 D111 → avg 1.9 bits vs 2."},
            {"topic": "CD & DVD", "line": "Pits & lands on a spiral, read by laser. CD 700 MB (780 nm), DVD 4.7–17 GB (650 nm, tighter spiral)."},
            {"topic": "Streaming/VoD", "line": "Play while downloading; buffer absorbs hiccups; adaptive quality. VoD = watch anytime; conferencing = 2-way live."},
            {"topic": "VR & AR", "line": "VR = fully virtual world via HMD + tracking + data glove. AR = overlay on the real world (phone/glasses)."},
            {"topic": "Project Stages", "line": "Plan (storyboard, budget) → Design (prototype) → Produce → Test (alpha/beta) → Deliver."},
            {"topic": "File Formats", "line": "JPEG photo · PNG logo/transparency · GIF 256+animation · WAV/MP3/MIDI audio · AVI/MP4 video."},
        ],
        "must_memorize": [
            {"term": "JPEG", "definition": "Lossy image-compression standard: 8×8 blocks → DCT → quantization (the main lossy step) → zig-zag + Huffman."},
            {"term": "DCT", "definition": "Discrete Cosine Transform — converts an image block into frequency values so tiny details can be discarded."},
            {"term": "MPEG", "definition": "Lossy video standard using I, P, B frames and motion compensation to remove redundancy between frames."},
            {"term": "I / P / B Frames", "definition": "I = complete independent frame; P = predicted from a previous reference frame (stores residuals); B = predicted from both neighbouring references (usually smallest)."},
            {"term": "Huffman Coding", "definition": "Lossless coding giving short codes to frequent symbols via a tree of merged probabilities; prefix-free."},
            {"term": "CD-ROM / DVD", "definition": "Optical discs storing data as pits and lands on a spiral read by laser; CD ≈ 700 MB, DVD ≈ 4.7 GB."},
            {"term": "Streaming", "definition": "Continuous delivery of media that plays while the rest downloads, using a small buffer."},
            {"term": "Video-on-Demand", "definition": "Service letting users watch any stored video at any time (e.g., YouTube, Netflix)."},
            {"term": "Virtual Reality", "definition": "Computer-generated 3D world the user enters and interacts with via HMD, tracking and data gloves."},
            {"term": "Augmented Reality", "definition": "Technology that overlays computer-generated images on the user's view of the REAL world."},
            {"term": "Storyboard", "definition": "Frame-by-frame sketch plan of every screen of a multimedia project, made before production."},
        ],
    },
}
