UNIT_1 = {
    "unit_id": "cg-unit-1",
    "unit_number": 1,
    "subject": "Computer Graphics & Multimedia",
    "title": "CG Unit 1 — Rapid Revision",
    "subtitle": "Only the must-know stuff · Read in under 1 hour",
    "course": "M.Sc CS Sem-IV · MGSU Bikaner",
    "topics": [
        {
            "id": "intro-cg",
            "number": 1,
            "title": "Introduction to Computer Graphics",
            "analogy": "Screen = board of tiny bulbs (pixels). The computer switches them ON/OFF in colours to paint any picture.",
            "definition": "Computer Graphics is the branch of computer science that creates, stores and displays pictures using a computer.",
            "working": [
                "User gives input (mouse/keyboard) → CPU/GPU converts it into a picture made of pixels.",
                "Pixel colour values are stored in memory called the frame buffer.",
                "Screen reads the frame buffer and shows the image.",
            ],
            "diagram_key": "intro-flow",
            "diagram_caption": "Graphics pipeline",
            "quick_facts": [
                "Pixel = smallest dot of the picture. Frame buffer = memory holding every pixel's value.",
                "Interactive (games, CAD) vs Non-interactive (movies, TV titles).",
                "Uses: CAD, games, GUI, animation, medical imaging (CT/MRI).",
            ],
            "comparison": None,
            "formulas": [],
            "memory_trick": "Applications = C-GAMES → CAD, GUI, Animation, Medical, Education, Simulation.",
            "exam_tip": None,
            "solved_example": None,
        },
        {
            "id": "display-devices",
            "number": 2,
            "title": "Display Devices",
            "analogy": "Different TVs at home — fat old TV (CRT) vs slim LED. Each makes the picture its own way.",
            "definition": "A display device is an output device that shows text and images from the computer in visual form.",
            "working": [
                "Two families: CRT-based (Raster scan, Random scan, DVST) and Flat Panel.",
                "Flat Panel Emissive = makes its own light (LED, Plasma).",
                "Flat Panel Non-Emissive = needs backlight (LCD).",
            ],
            "diagram_key": "display-tree",
            "diagram_caption": "Classification of display devices",
            "quick_facts": [
                "CRT: good colours but bulky, power hungry. LCD: thin, low power.",
                "DVST: stores picture on screen itself — no refresh needed, but no colour.",
            ],
            "comparison": None,
            "formulas": [],
            "memory_trick": "CRT is FAT, flat panel is FLAT. Emissive = Emits its own light.",
            "exam_tip": None,
            "solved_example": None,
        },
        {
            "id": "crt",
            "number": 3,
            "title": "CRT (Cathode Ray Tube)",
            "analogy": "A torch inside a glass bottle shooting a beam at a glowing wall — move it fast and the dots form a picture.",
            "definition": "CRT is a vacuum tube in which an electron gun fires a beam that is focused and deflected onto a phosphor screen, which glows to form the image.",
            "working": [
                "Electron gun (heated cathode) emits electrons.",
                "Control grid sets beam strength → brightness.",
                "Focusing anode sharpens the beam to a point.",
                "Deflection plates (horizontal + vertical) bend the beam to any (x, y).",
                "Beam hits phosphor screen → spot glows → spots form the picture.",
            ],
            "diagram_key": "crt",
            "diagram_caption": "CRT cross-section (most-repeated diagram!)",
            "quick_facts": [
                "Persistence = how long phosphor glows after the beam leaves.",
                "Refresh rate = 60–80 Hz (redraws/sec) to avoid flicker.",
                "Colour CRT = 3 guns (R,G,B) + shadow mask.",
            ],
            "comparison": None,
            "formulas": [],
            "memory_trick": "Beam path: Gun → Grid → Focus → Deflect → Screen.",
            "exam_tip": "Practice this diagram once on paper — it is almost guaranteed in the exam.",
            "solved_example": None,
        },
        {
            "id": "raster-scan",
            "number": 4,
            "title": "Raster Scan Display",
            "analogy": "Reading a book — line by line, left to right, top to bottom, then start again.",
            "definition": "In raster scan the beam sweeps the screen row by row (scan lines), lighting pixels using values stored in the frame buffer.",
            "working": [
                "Beam sweeps each line left → right (pixels ON/OFF from frame buffer).",
                "Horizontal retrace: beam OFF, jump to start of next line.",
                "Vertical retrace: from bottom back to top for the next frame.",
                "Whole screen refreshed ~60 times per second.",
            ],
            "diagram_key": "raster",
            "diagram_caption": "Raster scan with both retraces",
            "quick_facts": [
                "Needs frame buffer (stores EVERY pixel). Gives realistic shaded images (TV, monitors).",
                "Slanted lines look jagged — staircase/aliasing effect.",
            ],
            "comparison": None,
            "formulas": [],
            "memory_trick": "Raster = Reading a book. Don't forget the 2 retraces!",
            "exam_tip": None,
            "solved_example": None,
        },
        {
            "id": "random-scan",
            "number": 5,
            "title": "Random Scan Display (Vector)",
            "analogy": "Drawing with a pen — move only along the lines, never scribble the whole page.",
            "definition": "In random scan (vector display) the beam draws only the picture lines, one line at a time, using commands stored in a display file.",
            "working": [
                "Line commands (\"draw A to B\") stored in the display file.",
                "Beam jumps to the start point and draws each line.",
                "All lines redrawn 30–60 times/sec to refresh.",
            ],
            "diagram_key": "random",
            "diagram_caption": "Beam draws only the triangle edges: A→B→C→A",
            "quick_facts": [
                "Very smooth lines, but only wireframes — no shading.",
                "Used in early CAD, radar, oscilloscopes.",
            ],
            "comparison": {
                "title": "★ Raster vs Random (near-guaranteed 5-marker)",
                "headers": ["Point", "Raster", "Random"],
                "rows": [
                    ["Beam covers", "Whole screen, row by row", "Only the picture lines"],
                    ["Stores", "Pixels in frame buffer", "Commands in display file"],
                    ["Image", "Realistic, shaded", "Wireframe lines only"],
                    ["Lines", "Jagged (staircase)", "Very smooth"],
                    ["Used in", "TV, monitors", "CAD, radar"],
                ],
            },
            "formulas": [],
            "memory_trick": "Random = Ruler (lines only). Raster = Reading (rows).",
            "exam_tip": "Memorise the table — it alone can fetch full 5 marks.",
            "solved_example": None,
        },
        {
            "id": "rgb",
            "number": 6,
            "title": "RGB Colour Model",
            "analogy": "Three torches (R, G, B) on a dark wall — overlaps make new colours; all three together = WHITE.",
            "definition": "RGB is an ADDITIVE colour model: Red, Green and Blue lights are added to produce all colours. Used in monitors, TVs, cameras.",
            "working": [
                "Start from BLACK (no light) and ADD lights.",
                "R+G = Yellow, G+B = Cyan, R+B = Magenta.",
                "R+G+B = White; R = G = B gives grey shades.",
            ],
            "diagram_key": "rgb",
            "diagram_caption": "Additive mixing (dark background)",
            "quick_facts": [
                "The word ADDITIVE is compulsory in the answer.",
            ],
            "comparison": None,
            "formulas": ["24-bit colour: 2^24 = 16.7 million colours"],
            "memory_trick": "RGB = SCREEN. Add lights, all ON = White, no light = Black.",
            "exam_tip": None,
            "solved_example": None,
        },
        {
            "id": "cmy",
            "number": 7,
            "title": "CMY / CMYK Colour Model",
            "analogy": "Inks on white paper absorb (subtract) light — more ink = darker. All inks = black.",
            "definition": "CMY is a SUBTRACTIVE model: Cyan, Magenta, Yellow inks remove colours from white light. K (black ink) is added for sharp, cheap black → CMYK. Used in printers.",
            "working": [
                "Start from WHITE paper; each ink removes one colour.",
                "C absorbs Red, M absorbs Green, Y absorbs Blue.",
                "C+M+Y = muddy black → add K (Key/black) ink.",
            ],
            "diagram_key": "cmy",
            "diagram_caption": "Subtractive mixing (white background)",
            "quick_facts": [
                "The word SUBTRACTIVE is compulsory in the answer.",
            ],
            "comparison": {
                "title": "★ RGB vs CMY (common 5-marker)",
                "headers": ["Point", "RGB", "CMY/CMYK"],
                "rows": [
                    ["Type", "Additive (adds light)", "Subtractive (removes light)"],
                    ["Starts from", "Black", "White (paper)"],
                    ["All mixed", "White", "Black"],
                    ["Used in", "Monitors, TV", "Printers"],
                ],
            },
            "formulas": ["C = 1 − R,   M = 1 − G,   Y = 1 − B"],
            "memory_trick": "RGB for SCREEN, CMYK for PRINT. C kills R, M kills G, Y kills B.",
            "exam_tip": None,
            "solved_example": None,
        },
        {
            "id": "hsv",
            "number": 8,
            "title": "HSV Colour Model",
            "analogy": "Pick colour like an artist: WHICH colour (H), HOW pure (S), HOW bright (V).",
            "definition": "HSV describes colour by Hue (colour type, angle 0°–360°), Saturation (purity, 0–1) and Value (brightness, 0–1). Drawn as an inverted hexcone with black at the tip.",
            "working": [
                "Hue = angle on wheel: 0° Red, 120° Green, 240° Blue (gap of 60°: Y, C, M in between).",
                "Saturation = centre (0 = grey) → edge (1 = pure colour).",
                "Value = height: 0 = Black (tip), 1 = brightest (white at top centre).",
            ],
            "diagram_key": "hsv",
            "diagram_caption": "HSV wheel (Hue = angle) + inverted hexcone (Value = height)",
            "quick_facts": [
                "S = 0 gives the grey axis (black → white). Used in colour pickers (Paint/Photoshop).",
            ],
            "comparison": None,
            "formulas": ["H ∈ [0°, 360°],  S ∈ [0, 1],  V ∈ [0, 1]"],
            "memory_trick": "H = which colour, S = how pure, V = how bright.",
            "exam_tip": "Write HSV only — NEVER write HSI. It can cost the full question.",
            "solved_example": None,
        },
        {
            "id": "dda",
            "number": 9,
            "title": "DDA Line Drawing Algorithm",
            "analogy": "Climb a slope in equal baby steps — each step, stand on the NEAREST tile (pixel).",
            "definition": "DDA (Digital Differential Analyzer) draws a line by adding small fixed increments to x and y at each step and rounding to the nearest pixel.",
            "working": [
                "Δx = x2 − x1, Δy = y2 − y1.",
                "Steps = max(|Δx|, |Δy|).",
                "x-inc = Δx/Steps, y-inc = Δy/Steps.",
                "From (x1, y1): keep adding increments, plot round(x), round(y) each time.",
            ],
            "diagram_key": "dda-grid",
            "diagram_caption": "Pixels plotted for (2,3) → (8,6)",
            "quick_facts": [
                "Simple & fast (only additions), but floating point + rounding. Bresenham fixes this with integers.",
            ],
            "comparison": None,
            "formulas": ["Steps = max(|Δx|, |Δy|)   ·   inc = Δ / Steps"],
            "memory_trick": "Divide once, then Add-Add-Add. Rule: 0.5 always rounds UP.",
            "exam_tip": None,
            "solved_example": {
                "title": "Solved: (2, 3) → (8, 6)",
                "given": "Δx = 6, Δy = 3 → Steps = 6 → x-inc = 1, y-inc = 0.5",
                "steps": [],
                "table": {
                    "headers": ["k", "x", "y", "Plot"],
                    "rows": [
                        ["0", "2", "3.0", "(2, 3)"],
                        ["1", "3", "3.5", "(3, 4)"],
                        ["2", "4", "4.0", "(4, 4)"],
                        ["3", "5", "4.5", "(5, 5)"],
                        ["4", "6", "5.0", "(6, 5)"],
                        ["5", "7", "5.5", "(7, 6)"],
                        ["6", "8", "6.0", "(8, 6)"],
                    ],
                },
                "note": "3.5→4, 4.5→5, 5.5→6 (0.5 rounds UP). Last row = end point (8,6) ✓. Total 7 pixels.",
            },
        },
        {
            "id": "scan-conversion",
            "number": 10,
            "title": "Scan Conversion (Rasterization)",
            "analogy": "Turning a smooth sketch into LEGO art — the shape gets rebuilt from small square blocks (pixels).",
            "definition": "Scan conversion (rasterization) is converting geometric shapes (lines, circles, polygons) into pixels so a raster display can show them.",
            "working": [
                "Shape defined by maths (e.g., line = 2 end points).",
                "Algorithm (DDA / Bresenham / Midpoint) picks the nearest pixels.",
                "Pixel values go to the frame buffer → screen lights them.",
            ],
            "diagram_key": "scan-flow",
            "diagram_caption": "Primitive → Algorithm → Frame buffer → Screen",
            "quick_facts": [
                "Jagged edges = ALIASING; smoothing it = ANTIALIASING.",
            ],
            "comparison": None,
            "formulas": [],
            "memory_trick": "Shape → Squares. Pipeline: P-A-F-S (Primitive, Algorithm, Frame buffer, Screen).",
            "exam_tip": None,
            "solved_example": None,
        },
    ],
    "final_sections": {
        "last_minute_revision": [
            {"topic": "Computer Graphics", "line": "Making pictures by computer. Pixel = smallest dot. Frame buffer = pixel memory. Apps: CAD, games, GUI, medical."},
            {"topic": "Display Devices", "line": "CRT-based (raster, random, DVST) vs Flat panel (Emissive: LED/Plasma · Non-emissive: LCD)."},
            {"topic": "CRT", "line": "Gun → Grid (brightness) → Focus → Deflect → Phosphor glows. Persistence + refresh 60–80 Hz."},
            {"topic": "Raster Scan", "line": "Row by row like reading. Frame buffer. 2 retraces (horizontal + vertical). Realistic images."},
            {"topic": "Random Scan", "line": "Beam draws only lines. Display file stores commands. Smooth wireframes. CAD/radar."},
            {"topic": "RGB", "line": "ADDITIVE, screens. Black start. R+G=Y, G+B=C, R+B=M, all = White. 2^24 = 16.7M colours."},
            {"topic": "CMY/CMYK", "line": "SUBTRACTIVE, printers. White start. C=1−R, M=1−G, Y=1−B. K = real black ink."},
            {"topic": "HSV", "line": "Hue = angle 0–360°, Saturation = purity 0–1, Value = brightness 0–1. Inverted hexcone, black tip. NEVER write HSI."},
            {"topic": "DDA", "line": "Steps = max(|Δx|,|Δy|), inc = Δ/Steps, add & round. (2,3)→(8,6): Steps 6, x-inc 1, y-inc 0.5. 0.5 rounds UP."},
            {"topic": "Scan Conversion", "line": "Shape → pixels. Primitive → Algorithm → Frame buffer → Screen. Jagged = aliasing."},
        ],
        "must_memorize": [
            {"term": "Pixel", "definition": "Smallest addressable picture element on the screen."},
            {"term": "Frame Buffer", "definition": "Memory that stores the colour/intensity value of every pixel."},
            {"term": "Persistence", "definition": "Time the phosphor keeps glowing after the beam moves away."},
            {"term": "Refresh Rate", "definition": "Times per second the picture is redrawn (60–80 Hz) to avoid flicker."},
            {"term": "CRT", "definition": "Vacuum tube where an electron gun fires a focused, deflected beam onto a phosphor screen to form images."},
            {"term": "Raster Scan", "definition": "Beam sweeps the screen row by row, lighting pixels from frame buffer values."},
            {"term": "Random Scan", "definition": "Beam draws only the picture lines, one at a time, from a display file."},
            {"term": "RGB / CMY", "definition": "RGB = additive (screens, all = white). CMY = subtractive (printers, all = black); C=1−R, M=1−G, Y=1−B."},
            {"term": "HSV", "definition": "Hue (angle 0–360°), Saturation (purity 0–1), Value (brightness 0–1); inverted hexcone."},
            {"term": "DDA", "definition": "Line algorithm: Steps = max(|Δx|,|Δy|); add Δ/Steps each step and round to nearest pixel."},
            {"term": "Scan Conversion", "definition": "Converting geometric shapes into pixels for a raster display."},
            {"term": "Aliasing", "definition": "Staircase (jagged) look of slanted lines due to square pixels."},
        ],
    },
}
