UNIT_4 = {
    "unit_id": "cg-unit-4",
    "unit_number": 4,
    "subject": "Computer Graphics & Multimedia",
    "title": "CG Unit 4 — Rapid Revision",
    "subtitle": "Multimedia basics · Text, image, audio, video, animation · Compression",
    "course": "M.Sc CS Sem-IV · MGSU Bikaner",
    "topics": [
        {
            "id": "intro-multimedia",
            "number": 1,
            "title": "Introduction to Multimedia",
            "analogy": "A textbook only has text. A movie with subtitles, music, pictures and clickable menus = many media working together — that is multimedia.",
            "definition": "Multimedia is the computer-controlled combination of two or more media — text, images, audio, video and animation — presented together, often with user interactivity.",
            "working": [
                "Linear multimedia: plays start to finish with no user control (e.g., a movie).",
                "Non-linear (interactive) multimedia: user controls the flow (e.g., games, websites, e-learning).",
                "Needs special hardware (sound card, graphics card, mic, speakers) + software (players, authoring tools).",
                "Hypermedia = multimedia + hyperlinks connecting the content.",
            ],
            "diagram_key": None,
            "diagram_caption": None,
            "quick_facts": [
                "Applications: education (e-learning), entertainment (games, movies), medicine (3D scans), business (presentations, ads), virtual reality.",
            ],
            "comparison": None,
            "formulas": [],
            "memory_trick": "Multi = many, Media = ways of expressing. Linear = movie, Non-linear = game.",
            "exam_tip": "Always write the word INTERACTIVITY in the definition — it separates multimedia from ordinary video.",
            "solved_example": None,
        },
        {
            "id": "mm-components",
            "number": 2,
            "title": "Components of Multimedia",
            "analogy": "A thali (food platter): five different dishes served together make the full meal — five media together make multimedia.",
            "definition": "The five components (building blocks) of multimedia are Text, Images, Audio, Video and Animation.",
            "working": [
                "Text: the base of all multimedia — headings, menus, subtitles (fonts, styles).",
                "Images: photos and drawings — bitmap (pixels) or vector (maths).",
                "Audio: speech, music, sound effects — digitized sound or MIDI.",
                "Video: moving real-camera pictures — frames shown fast (25–30 fps).",
                "Animation: moving DRAWN pictures — created frame by frame or by tweening.",
            ],
            "diagram_key": "mm-components",
            "diagram_caption": "Five building blocks of multimedia",
            "quick_facts": [
                "Video captures the real world; animation is artificially drawn — this one-line difference is often asked.",
            ],
            "comparison": None,
            "formulas": [],
            "memory_trick": "T-I-A-V-A → \"TIAVA\": Text, Image, Audio, Video, Animation.",
            "exam_tip": None,
            "solved_example": None,
        },
        {
            "id": "text-images",
            "number": 3,
            "title": "Text & Images (Bitmap vs Vector)",
            "analogy": "Bitmap = a rangoli made of tiny dots (zoom in and you see the dots). Vector = a drawing made with a compass and ruler (redrawn perfectly at any size).",
            "definition": "A bitmap (raster) image stores colour values of every pixel in a grid; a vector image stores mathematical drawing instructions (lines, curves). Text in multimedia uses fonts — serif, sans-serif and decorative.",
            "working": [
                "Bitmap: photo-realistic, big file, becomes jagged (pixelated) when enlarged. Formats: BMP, JPEG, GIF, PNG.",
                "Vector: logos/diagrams, small file, perfectly smooth at ANY zoom. Formats: SVG, WMF, CDR.",
                "Image size (bytes) = Width × Height × (bit depth ÷ 8).",
                "Colour depth: 8-bit = 256 colours, 24-bit = 16.7 million (true colour).",
            ],
            "diagram_key": "bitmap-vector",
            "diagram_caption": "Bitmap = pixel grid (jaggy on zoom) · Vector = maths (always smooth)",
            "quick_facts": [
                "JPEG = lossy photos · GIF = 256 colours + animation · PNG = lossless + transparency · BMP = uncompressed.",
            ],
            "comparison": {
                "title": "★ Bitmap vs Vector (common 5-marker)",
                "headers": ["Point", "Bitmap (Raster)", "Vector"],
                "rows": [
                    ["Stores", "Colour of every pixel", "Maths formulas (lines, curves)"],
                    ["On zooming", "Jagged / pixelated", "Always smooth"],
                    ["File size", "Large", "Small"],
                    ["Best for", "Photographs", "Logos, diagrams, fonts"],
                ],
            },
            "formulas": ["Image size = W × H × (bit depth ÷ 8) bytes"],
            "memory_trick": "Bitmap = Bits on a map (pixels). Vector = maths — V for 'variable size, no damage'.",
            "exam_tip": None,
            "solved_example": {
                "title": "Solved: size of an 800 × 600, 24-bit image",
                "given": "W = 800, H = 600, depth = 24 bits = 3 bytes/pixel",
                "steps": [],
                "table": {
                    "headers": ["Step", "Calculation", "Result"],
                    "rows": [
                        ["Pixels", "800 × 600", "4,80,000"],
                        ["Bytes", "4,80,000 × 3", "14,40,000 B"],
                        ["Size", "14,40,000 ÷ 10⁶", "≈ 1.44 MB"],
                    ],
                },
                "note": "Uncompressed. JPEG can shrink this ~10× with barely visible loss — that is why photos use JPEG.",
            },
        },
        {
            "id": "digital-audio",
            "number": 4,
            "title": "Digital Audio & MIDI",
            "analogy": "Digitizing sound = taking thousands of photos of a moving wave every second. More photos per second (sampling) + more detail per photo (bit depth) = truer sound.",
            "definition": "Digital audio is sound converted to numbers by sampling (measuring the wave thousands of times per second) and quantization (storing each sample in fixed bits). MIDI instead stores musical instructions (which note, which instrument), not the sound itself.",
            "working": [
                "Sampling rate = samples per second (CD quality = 44,100 Hz = 44.1 kHz).",
                "Bit depth = bits per sample (CD = 16-bit); more bits = finer loudness steps.",
                "Channels: mono = 1, stereo = 2.",
                "File size = sampling rate × bit depth × channels × time ÷ 8 bytes.",
            ],
            "diagram_key": "audio-sampling",
            "diagram_caption": "Analog wave → samples → bits (sampling + quantization)",
            "quick_facts": [
                "Formats: WAV (uncompressed), MP3 (lossy compressed), MIDI (instructions only, tiny files).",
            ],
            "comparison": {
                "title": "★ MIDI vs Digital Audio (common 5-marker)",
                "headers": ["Point", "MIDI", "Digital Audio"],
                "rows": [
                    ["Stores", "Note instructions (recipe)", "Actual sound wave (dish)"],
                    ["File size", "Very small", "Large"],
                    ["Can record voice?", "No — instruments only", "Yes, any sound"],
                    ["Playback", "Depends on device sounds", "Same everywhere"],
                ],
            },
            "formulas": ["Audio size = rate × bits × channels × time ÷ 8 bytes"],
            "memory_trick": "MIDI = recipe (notes to play). Digital audio = cooked dish (the sound itself).",
            "exam_tip": None,
            "solved_example": {
                "title": "Solved: 10 seconds of CD-quality stereo audio",
                "given": "rate = 44,100 Hz · bits = 16 · channels = 2 · time = 10 s",
                "steps": [],
                "table": {
                    "headers": ["Step", "Calculation", "Result"],
                    "rows": [
                        ["Bits", "44100 × 16 × 2 × 10", "1,41,12,000 bits"],
                        ["Bytes", "÷ 8", "17,64,000 B"],
                        ["Size", "÷ 10⁶", "≈ 1.76 MB"],
                    ],
                },
                "note": "Just 10 seconds ≈ 1.76 MB uncompressed — MP3 compresses this ~10× by throwing away sounds the ear cannot notice.",
            },
        },
        {
            "id": "digital-video",
            "number": 5,
            "title": "Digital Video",
            "analogy": "A flip-book: many still pictures flipped fast look like motion. Video = 25–30 photos (frames) every second.",
            "definition": "Digital video is a sequence of still images (frames) displayed rapidly (measured in frames per second, fps) to create the illusion of motion, usually with synchronized audio.",
            "working": [
                "Frame rate: PAL = 25 fps (India/Europe), NTSC = 30 fps (USA); below ~16 fps motion looks jerky.",
                "Each frame is a bitmap: frame size = W × H × bytes per pixel.",
                "Uncompressed video is HUGE → always stored compressed (MPEG, MP4/H.264).",
                "Formats: AVI, MOV, MP4, MPEG; streaming sends video in a continuous flow.",
            ],
            "diagram_key": "video-frames",
            "diagram_caption": "Still frames played fast (25 fps) = motion",
            "quick_facts": [
                "Video = real camera capture; animation = drawn frames. MPEG stores only CHANGES between frames.",
            ],
            "comparison": None,
            "formulas": ["Video size = W × H × 3 × fps × seconds (24-bit, uncompressed)"],
            "memory_trick": "PAL = Pachees (25) fps. Flip-book = frames per second.",
            "exam_tip": None,
            "solved_example": {
                "title": "Solved: 10 s of 640 × 480, 24-bit video at 25 fps",
                "given": "One frame = 640 × 480 × 3 bytes",
                "steps": [],
                "table": {
                    "headers": ["Step", "Calculation", "Result"],
                    "rows": [
                        ["Frame size", "640 × 480 × 3", "9,21,600 B"],
                        ["Per second", "× 25 fps", "≈ 23 MB/s"],
                        ["10 seconds", "× 10", "≈ 230 MB!"],
                    ],
                },
                "note": "230 MB for just 10 seconds — this single number is the perfect exam answer to \"why is video compression necessary?\"",
            },
        },
        {
            "id": "animation",
            "number": 6,
            "title": "Animation",
            "analogy": "Drawing a cricket ball at slightly different spots on 24 pages and flipping them — the ball 'flies'. You draw only the key positions; the computer fills the rest.",
            "definition": "Animation is the rapid display of a sequence of DRAWN images to create the illusion of movement. In computer animation the artist draws key frames and the software generates the in-between frames (tweening).",
            "working": [
                "Traditional (cel) animation: every frame drawn by hand on transparent sheets (cels).",
                "Keyframe animation: artist sets start & end poses (keyframes); computer TWEENS the in-betweens.",
                "Morphing: smoothly transforming one image into another.",
                "2D animation = flat drawings; 3D animation = models + lighting (Pixar-style). Smooth motion needs ~24 fps.",
            ],
            "diagram_key": "keyframe-tween",
            "diagram_caption": "Keyframes drawn by artist, tweens generated by computer",
            "quick_facts": [
                "Animation vs video: animation is created/drawn, video is captured from the real world.",
            ],
            "comparison": None,
            "formulas": [],
            "memory_trick": "KEY frames by the artist, tWEENs by the machine (in-betWEENs).",
            "exam_tip": None,
            "solved_example": None,
        },
        {
            "id": "compression",
            "number": 7,
            "title": "Data Compression (Lossless & Lossy)",
            "analogy": "Packing a suitcase: lossless = folding clothes tightly (everything comes back perfect); lossy = leaving behind clothes you will never notice missing (smaller bag, tiny sacrifice).",
            "definition": "Data compression reduces file size by removing redundancy. Lossless compression restores the data EXACTLY (RLE, Huffman); lossy compression permanently discards less-important detail for much bigger savings (JPEG, MP3, MPEG).",
            "working": [
                "RLE (Run Length Encoding): replace repeated runs by count + symbol (AAAA → 4A).",
                "Huffman coding: frequent symbols get SHORT codes, rare symbols get LONG codes.",
                "JPEG (images), MP3 (audio), MPEG (video) are lossy — they exploit human eye/ear limits.",
                "Compression ratio = original size ÷ compressed size.",
            ],
            "diagram_key": "compression-tree",
            "diagram_caption": "Compression family tree",
            "quick_facts": [
                "Text/programs MUST use lossless (one wrong bit breaks them); photos/music can afford lossy.",
            ],
            "comparison": {
                "title": "★ Lossless vs Lossy (very common 5-marker)",
                "headers": ["Point", "Lossless", "Lossy"],
                "rows": [
                    ["Original recovered?", "Exactly, bit by bit", "Never — detail discarded"],
                    ["Compression amount", "Moderate (2–4×)", "High (10–100×)"],
                    ["Techniques", "RLE, Huffman", "JPEG, MP3, MPEG"],
                    ["Used for", "Text, programs, PNG/GIF/ZIP", "Photos, audio, video"],
                ],
            },
            "formulas": ["Compression ratio = original size ÷ compressed size"],
            "memory_trick": "Lossless = zip it back perfectly. Lossy = throw a little, save a lot.",
            "exam_tip": None,
            "solved_example": {
                "title": "Solved: RLE on the string AAAABBBCCD",
                "given": "Replace each run by (count, symbol)",
                "steps": [],
                "table": {
                    "headers": ["Run", "Encoding", "Characters"],
                    "rows": [
                        ["AAAA", "4A", "2"],
                        ["BBB", "3B", "2"],
                        ["CC", "2C", "2"],
                        ["D", "1D", "2"],
                    ],
                },
                "note": "Original 10 characters → compressed 8 (4A3B2C1D). Ratio = 10 ÷ 8 = 1.25. RLE shines on long runs (e.g., fax images, screenshots).",
            },
        },
        {
            "id": "mm-applications",
            "number": 8,
            "title": "Multimedia Applications & Authoring Tools",
            "analogy": "Authoring tool = a kitchen where all ingredients (text, audio, video, animation) are combined into one final dish (the multimedia application) without hard coding.",
            "definition": "Multimedia authoring tools are software used to combine and synchronize text, images, audio, video and animation into one interactive application. Types: card-based, icon-based and time-based tools.",
            "working": [
                "Card/page-based: content arranged as linked pages (HyperCard, ToolBook).",
                "Icon/flow-based: flowchart of icons decides the sequence (Authorware).",
                "Time-based: content arranged on a timeline of frames (Director, Flash).",
                "Applications: e-learning, games, movies/VFX, medical imaging & surgery training, virtual reality, advertising, video conferencing.",
            ],
            "diagram_key": None,
            "diagram_caption": None,
            "quick_facts": [
                "Multimedia PC needs: sound card, graphics card, CD/DVD drive, speakers, mic, high RAM/storage.",
            ],
            "comparison": None,
            "formulas": [],
            "memory_trick": "Authoring types = C-I-T: Card (pages), Icon (flowchart), Time (timeline).",
            "exam_tip": "For a 10-marker on applications, give 6 fields with ONE example each — breadth beats depth here.",
            "solved_example": None,
        },
    ],
    "final_sections": {
        "cheat_card": {
            "read_time": "2-minute read",
            "formulas": [
                "Image size = W × H × (bit depth ÷ 8) bytes",
                "Audio size = rate × bits × channels × time ÷ 8",
                "CD audio = 44.1 kHz, 16-bit, stereo",
                "Video size = W × H × 3 × fps × seconds (24-bit)",
                "PAL 25 fps · NTSC 30 fps · smooth ≈ 24 fps",
                "Compression ratio = original ÷ compressed",
                "RLE: AAAABBBCCD → 4A3B2C1D (10 → 8)",
            ],
            "hooks": [
                "Components = T-I-A-V-A: Text, Image, Audio, Video, Animation",
                "Bitmap = pixels (jaggy zoom) · Vector = maths (smooth)",
                "MIDI = recipe · Digital audio = cooked dish",
                "Video = captured real world · Animation = drawn frames",
                "KEY frames by artist, tWEENs by machine",
                "Lossless = zip back perfect (RLE, Huffman) · Lossy = throw a little (JPEG, MP3, MPEG)",
                "Authoring = C-I-T: Card, Icon, Time-based",
            ],
        },
        "last_minute_revision": [
            {"topic": "Multimedia", "line": "2+ media (text/image/audio/video/animation) + INTERACTIVITY. Linear = movie, non-linear = game."},
            {"topic": "Components", "line": "T-I-A-V-A. Video = captured; animation = drawn — one-line difference often asked."},
            {"topic": "Text & Images", "line": "Bitmap = pixels, jaggy zoom, photos (JPEG/GIF/PNG/BMP). Vector = maths, smooth, logos (SVG). Size = W×H×depth/8."},
            {"topic": "Audio", "line": "Sampling (44.1 kHz) + quantization (16-bit). Size = rate×bits×ch×t/8. MIDI = note instructions, tiny."},
            {"topic": "Video", "line": "Frames per second: PAL 25, NTSC 30. 10 s of 640×480 uncompressed ≈ 230 MB → must compress (MPEG)."},
            {"topic": "Animation", "line": "Drawn frames shown fast (~24 fps). Keyframes by artist, tweening by computer. Morphing = image A → B."},
            {"topic": "Compression", "line": "Lossless = exact (RLE, Huffman; text). Lossy = discard detail (JPEG/MP3/MPEG; media). Ratio = orig ÷ comp."},
            {"topic": "Authoring Tools", "line": "Card (ToolBook), Icon (Authorware), Time-based (Director/Flash). Apps: e-learning, games, medicine, VR, ads."},
        ],
        "must_memorize": [
            {"term": "Multimedia", "definition": "Computer-controlled combination of two or more media (text, image, audio, video, animation), usually interactive."},
            {"term": "Hypermedia", "definition": "Multimedia connected through hyperlinks that let the user jump between content."},
            {"term": "Bitmap Image", "definition": "Image stored as a grid of pixels; photo-realistic but jagged when enlarged."},
            {"term": "Vector Image", "definition": "Image stored as mathematical drawing instructions; smooth at any zoom, small file."},
            {"term": "Sampling", "definition": "Measuring an analog sound wave thousands of times per second to digitize it (CD = 44,100 Hz)."},
            {"term": "Quantization", "definition": "Storing each audio sample in a fixed number of bits (CD = 16-bit)."},
            {"term": "MIDI", "definition": "Musical Instrument Digital Interface — stores note/instrument instructions, not actual sound; very small files."},
            {"term": "Frame Rate", "definition": "Frames shown per second in video/animation: PAL 25 fps, NTSC 30 fps; ~24 fps looks smooth."},
            {"term": "Tweening", "definition": "Computer generation of in-between frames from the artist's keyframes."},
            {"term": "Lossless vs Lossy", "definition": "Lossless (RLE, Huffman) restores data exactly; lossy (JPEG, MP3, MPEG) discards detail for far smaller files."},
        ],
    },
}
